"""post to ships update

Revision ID: 2047c55631e2
Revises: befe3ea5ccaa
Create Date: 2019-06-26 14:50:48.978574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2047c55631e2'
down_revision = 'befe3ea5ccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('gunner_agility', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('helmsman_agility', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('ship_name', sa.String(length=30), nullable=True))
    op.add_column('post', sa.Column('ship_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'ship_type')
    op.drop_column('post', 'ship_name')
    op.drop_column('post', 'helmsman_agility')
    op.drop_column('post', 'gunner_agility')
    # ### end Alembic commands ###
